spring:
  profiles:
    include:
      # application-secrets.yaml
      - secrets
server:
  port: 8080
converter:
  uri-api: http://localhost:8082/api/v1/file
  uri-data: http://localhost:8081/api/v1/files