spring:
  profiles:
    include:
      # application-secrets.yaml
      - secrets
server:
  port: 8080
feign:
  client:
    api:
      uri: http://localhost:8082/api/v1/file
    data:
      uri: http://localhost:8081/api/v1